pipeline:

  docker:
    image: plugins/docker
    storage_driver: vfs
    repo: omelhoro1/slovene-lessons
    secrets: [ docker_username, docker_password ]
    when:
      branch: master

  deploy:
    image: omelhoro1/drone-rsync
    user: captain
    hosts: [ "software-unchained.com" ]
    port: 22
    target: /tmp/slovene-lessons-${DRONE_COMMIT}/
    include:
      - "docker-compose.yml"
    exclude:
      - "**.*"
    delete: false
    secrets: [ rsync_key ]
    script:
      - docker-compose -f /tmp/slovene-lessons-${DRONE_COMMIT}/docker-compose.yml pull
      - docker-compose -f /tmp/slovene-lessons-${DRONE_COMMIT}/docker-compose.yml -p slovene-lessons up -d
    when:
      branch: master
