version: '2'
services:
  slovene-lessons:
    image: omelhoro1/slovene-lessons
    container_name: slovene-lessons
    restart: unless-stopped
    # ports:
    #   - "5000:5000"
    labels:
      - "traefik.port=5000"
    networks:
      - proxy-tier
networks:
  proxy-tier:
    external: true
