version: '2'
services:
  slovene-lessons:
    image: omelhoro1/slovene-lessons
    container_name: slovene-lessons
    restart: unless-stopped
    # ports:
    #   - "5000:5000"
    environment:
      - VIRTUAL_HOST=slovene-lessons.igor-fischer.rocks,langapps.fischerops.com
      - LETSENCRYPT_HOST=slovene-lessons.igor-fischer.rocks,langapps.fischerops.com
      - VIRTUAL_NETWORK=proxy-tier
      - VIRTUAL_PORT=5000
      - LETSENCRYPT_EMAIL=fischerig@outlook.com
    networks:
      - proxy-tier
networks:
  proxy-tier:
    external: true
