name: slovapps
description: A sample web application
dependencies:
  bootjack: any
  browser: any
  dquery: any
  polymer: '>=0.13.0'
  shelf: any
  shelf_static: any
transformers:
- polymer:
    entry_points: web/index.html
