name: slovapps
description: A sample web application
dependencies:
  bootjack: 0.6.5+3
  browser: any
  dquery: 0.7.1+1
  polymer: '>=0.13.0'
  shelf: any
  shelf_static: any
transformers:
- polymer:
    entry_points: web/index.html
